//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCVMSR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }

        [Key]
        public int IdEmpleado { get; set; }

        [Display(Name = "Nombre")]
        [StringLength(100, ErrorMessage = "El nombre debe ser de 100 máximo.")]
        [Required(ErrorMessage = "Digite el nombre.")]
        [RegularExpression(@"^[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\s'-]+$", ErrorMessage = "Solo se permiten letras, incluyendo acentos, ñ, apóstrofes (') y guiones (-).")]
        public string Nombre { get; set; }

        [Display(Name = "Cédula")]
        [StringLength(20, ErrorMessage = "La cédula debe ser de 20 máximo.")]
        [Required(ErrorMessage = "Digite la cédula.")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Solo se permiten números.")]
        //[CedulaExiste(ErrorMessage = "La cédula ya existe.")]
        public string Cedula { get; set; }

        [Display(Name = "Segundo Nombre")]
        [StringLength(100, ErrorMessage = "El segundo nombre debe ser de 100 máximo.")]
        [Required(ErrorMessage = "Si el funcionario no tiene este dato colocar NO.")]
        [RegularExpression(@"^[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\s'-]+$", ErrorMessage = "Solo se permiten letras, incluyendo acentos, ñ, apóstrofes (') y guiones (-).")]
        public string SegundoNombre { get; set; }

        [Display(Name = "Primer Apellido")]
        [StringLength(100, ErrorMessage = "El primer apellido debe ser de 100 máximo.")]
        [Required(ErrorMessage = "Digite el primer apellido.")]
        [RegularExpression(@"^[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\s'-]+$", ErrorMessage = "Solo se permiten letras, incluyendo acentos, ñ, apóstrofes (') y guiones (-).")]
        public string PrimerApellido { get; set; }


        [Display(Name = "Segundo Apellido")]
        [StringLength(100, ErrorMessage = "El segundo apellido debe ser de 100 máximo.")]
        [Required(ErrorMessage = "Digite el segundo apellido.")]
        [RegularExpression(@"^[a-zA-ZáéíóúüñÁÉÍÓÚÜÑ\s'-]+$", ErrorMessage = "Solo se permiten letras, incluyendo acentos, ñ, apóstrofes (') y guiones (-).")]

        public string SegundoApellido { get; set; }

        [Display(Name = "Fecha Nacimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Digite la fecha de nacimiento.")]
        public Nullable<System.DateTime> FechaNacimiento { get; set; }

        [Display(Name = "Fecha Contratación")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Digite la fecha de contratación.")]
        public Nullable<System.DateTime> FechaContratacion { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdPuesto { get; set; }

        [Display(Name = "Correo")]
        [StringLength(50, ErrorMessage = "El correo debe ser de 50 máximo.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Digite un correo válido.")]
        [Required(ErrorMessage = "Digite el correo.")]
        public string CorreoElectronico { get; set; }

        [Display(Name = "Teléfono")]
        [StringLength(8, ErrorMessage = "El teléfono debe ser de 8 máximo.")]
        [RegularExpression(@"^\d{8}$", ErrorMessage = "El teléfono debe contener solo números y tener exactamente 8 dígitos.")]
        [Required(ErrorMessage = "Digite el teléfono.")]
        public string Telefono { get; set; }
        public Nullable<bool> Estado { get; set; }

        [Display(Name = "Saldo")]
        [Required(ErrorMessage = "Digite el saldo.")]
        public int Saldo { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }

        [Range(0, 100000000, ErrorMessage = "El salario debe ser un valor entre 0 y 100,000,000.")]
        [Required(ErrorMessage = "Digite el salario.")]
        public decimal Salario { get; set; }

        [NotMapped] // Este atributo indica que este campo no se almacenará en la base de datos
        public decimal ValorDiasSaldo { get; set; }

        [NotMapped]
        public bool IsEdit { get; set; }

        public virtual Departamentos Departamentos { get; set; }

        public virtual Puestos Puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }

        //public class CedulaExiste : ValidationAttribute
        //{
        //    protected override ValidationResult IsValid(Object value, ValidationContext validationContext)
        //    {
        //        var empleado = (Empleados)validationContext.ObjectInstance; // Obtener la instancia del modelo.
        //        using (SCVMSREntities db = new SCVMSREntities())
        //        {
        //            string cedula = (string)value; // Convertir el valor a string.

        //            // Si es una operación de edición, verificar si la cédula existe para otro empleado.
        //            if (empleado.IsEdit)
        //            {
        //                if (db.Empleados.Any(x => x.Cedula == cedula && x.IdEmpleado != empleado.IdEmpleado))
        //                {
        //                    return new ValidationResult("La cédula ya existe para otro empleado.");
        //                }
        //            }
        //            else
        //            {
        //                // Si es una operación de creación, verificar si la cédula ya existe en general.
        //                if (db.Empleados.Any(x => x.Cedula == cedula))
        //                {
        //                    return new ValidationResult("La cédula ya existe.");
        //                }
        //            }
        //        }

        //        return ValidationResult.Success;
        //    }
        //}

    }
}