//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCVMSR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCVMSREntities : DbContext
    {
        public SCVMSREntities()
            : base("name=SCVMSREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<Solicitudes> Solicitudes { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    
        public virtual int CalcularValorDiasDisfrute(Nullable<int> idEmpleado, ObjectParameter valorDiasDisfrute)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalcularValorDiasDisfrute", idEmpleadoParameter, valorDiasDisfrute);
        }
    
        public virtual int DescontarSaldo(Nullable<int> idSolicitud)
        {
            var idSolicitudParameter = idSolicitud.HasValue ?
                new ObjectParameter("IdSolicitud", idSolicitud) :
                new ObjectParameter("IdSolicitud", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DescontarSaldo", idSolicitudParameter);
        }
    
        public virtual ObjectResult<GenerarResumenMesAnteriorPDF_Result> GenerarResumenMesAnteriorPDF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerarResumenMesAnteriorPDF_Result>("GenerarResumenMesAnteriorPDF");
        }
    
        public virtual ObjectResult<MostrarEmpleados_Result> MostrarEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarEmpleados_Result>("MostrarEmpleados");
        }
    
        public virtual ObjectResult<MostrarEmpleadosActivos_Result> MostrarEmpleadosActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarEmpleadosActivos_Result>("MostrarEmpleadosActivos");
        }
    
        public virtual ObjectResult<MostrarEmpleadosInactivos_Result> MostrarEmpleadosInactivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarEmpleadosInactivos_Result>("MostrarEmpleadosInactivos");
        }
    
        public virtual ObjectResult<MostrarSolicitudesMesAnterior_Result> MostrarSolicitudesMesAnterior()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostrarSolicitudesMesAnterior_Result>("MostrarSolicitudesMesAnterior");
        }
    }
}
